name = "danogo2023/bond-issue"
version = "1.0.4"
license = "Apache-2.0"
description = "Danogo Bond Issue"

[repository]
user = "danogo2023"
project = "bond-issue"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.3"
source = "github"
